---
title: "Program Development and Validation Tracker"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Program Development and Validation Tracker}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<!-- Please update vignettes/pdvt.xlsx to reflect the validation information in current package.  -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  eval = FALSE,
  message = FALSE,
  echo = FALSE
)
```

```{r setup}
library(readxl)
library(knitr)
library(kableExtra)
library(pkgdown)
```

```{r, include=FALSE}
pkg <- pkgdown::as_pkgdown("..")

pdvt <- readxl::read_xlsx("pdvt.xlsx",
  sheet = "Plan and Track",
  skip = 2, .name_repair = "universal"
)
names(pdvt) <- tolower(gsub(".", "", names(pdvt), fixed = TRUE))

pdvt <- subset(pdvt, grepl(pkg$version, pdvt$roundnumber))
```

```{r}
overview <- pdvt[, c("programname", "overallprogramstatus", "description")]
names(overview) <- c("Name", "SDLC status", "Description")

sdlc <- pdvt[, c("programname", "programvalidationcategory", "who8", "who11", "who14", "who18", "who22")]
names(sdlc) <- c(
  "Name", "Validation Category", "Requestor",
  "Developer", "Double Programming", "Independent Test", "Customer Review"
)
```

## PDVT overview

```{r}
overview %>%
  kable(format = "html") %>%
  kable_styling()
```

## SDLC summary

```{r}
sdlc %>%
  kable(format = "html") %>%
  kable_styling()
```

> Full details of Program Development and Validation Tracker (PDVT) is located
> at <https://stash.merck.com/projects/BARDS/repos/rerandom/browse/vignettes/pdvt.xlsx>
