---
title: "Function Validation Plan"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Function Validation Plan}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  collapse = TRUE,
  eval = FALSE,
  message = FALSE
)
```

```{r}
library(magrittr)
library(rprojroot)
library(knitr)
library(kableExtra)
```

# Summary of testing plan 

> Validation details are located in the `tests/testthat/` folder.

```{r}
list_testing_case <- function() {
  pkg <- rprojroot::find_root("DESCRIPTION")

  filedir <- list.files(file.path(pkg, "tests/testthat"),
    pattern = "^test.*\\.[rR]$",
    full.names = TRUE
  )

  outlist <- lapply(filedir, function(x) {
    file <- basename(x)
    rtext <- readLines(x)
    test_raw <- rtext[grep("^test_that\\(", rtext)]
    test <- gsub("test_that\\(\"|\", \\{$", "", test_raw)
    return(data.frame(file, test))
  })

  res <- do.call("rbind", outlist)

  res
}
```

```{r}
list_testing_case() %>%
  kable(format = "html") %>%
  kable_styling()
```
